apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: marathon-secret
  namespace: statex-apps
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: marathon-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: secret/prod/marathon
        property: DATABASE_URL
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/prod/marathon
        property: DB_PASSWORD
    - secretKey: PAYMENT_API_KEY
      remoteRef:
        key: secret/prod/marathon
        property: PAYMENT_API_KEY
    - secretKey: PAYMENT_APPLICATION_ID
      remoteRef:
        key: secret/prod/marathon
        property: PAYMENT_APPLICATION_ID
    - secretKey: PAYMENT_WEBHOOK_API_KEY
      remoteRef:
        key: secret/prod/marathon
        property: PAYMENT_WEBHOOK_API_KEY
    - secretKey: SPEAKASAP_PORTAL_LEDGER_API_KEY
      remoteRef:
        key: secret/prod/marathon
        property: SPEAKASAP_PORTAL_LEDGER_API_KEY
    - secretKey: MARATHON_ADMIN_API_KEY
      remoteRef:
        key: secret/prod/marathon
        property: MARATHON_ADMIN_API_KEY

    - secretKey: JWT_TOKEN
      remoteRef:
        key: secret/prod/marathon
        property: JWT_TOKEN
    - secretKey: AUTH_INTERNAL_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/marathon
        property: AUTH_INTERNAL_SERVICE_TOKEN
    - secretKey: MARATHON_PORTAL_JWT_SECRET
      remoteRef:
        key: secret/prod/marathon
        property: MARATHON_PORTAL_JWT_SECRET
    - secretKey: AI_SERVICE_JWT_SECRET
      remoteRef:
        key: secret/prod/ai-microservice
        property: JWT_SECRET
