apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marathon
  namespace: statex-apps
  labels:
    app: marathon
    managed-by: k8s-migration
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - marathon.alfares.cz
      secretName: marathon-tls
  rules:
    - host: marathon.alfares.cz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: marathon
                port:
                  number: 3000
