apiVersion: v1
kind: Service
metadata:
  name: marathon
  namespace: statex-apps
  labels:
    app: marathon
    managed-by: k8s-migration
spec:
  type: ClusterIP
  selector:
    app: marathon
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
